controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 4 4 4 . . . . . . 
        . . . . . . . . . . . . 4 4 4 . 
        . . . . . . . . 4 4 4 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 100, 0)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Player, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
})
let projectile: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
mySprite = sprites.create(img`
    ....5555......................
    ..55555555....................
    .5555555555...................
    .555d555555...................
    .55ddd55555...................
    .55dddd5555...................
    .dddddddddd...................
    .ddffddffdd...................
    .dddddddddd...................
    .fdddffdddd...................
    .ffddddddff.f.................
    ddf666666fddfffff.............
    ddf666666fddff................
    ddf666666fddf.................
    ...ffffff..fff................
    ...ff..ff..fff................
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 55, 100)
let statusbar = statusbars.create(20, 4, StatusBarKind.Energy)
statusbar.positionDirection(CollisionDirection.Top)
forever(function () {
    mySprite = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......f41111114f.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd11111ddf......
        ......f4d42dd24d4f......
        ......f4d421124d4f......
        .......f4111111fffff....
        ....fffff4d41441114f....
        ....f411144f4f14141f....
        ....f14141ffff4f4f4f....
        ....f4f4...........f....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
})
